### ISSUE TITLE
patch file cant not fine here

### ISSUE THREAD

**Issue by peterfromthehill** [jcu-eresearch/nginx-custom-build#1]
Hi,

thx you for this build script.. help me a lot!

But one bug:

pushd ~/rpmbuild/SPECS
if [ -d "/vagrant" ]; then
    cp /vagrant/nginx-eresearch.patch ~/rpmbuild/SPECS/
    cp /vagrant/nginx-xslt-html-parser.patch ~/rpmbuild/SOURCES/
fi
patch -p1 < nginx-eresearch.patch

the nginx-eresearch.patch are not in ~/rpmbuild/SPECS/, he needs a path like the vagrant files.

best regards
peter from the hill!

**Comment by davidjb** [comment]
This script is was expecting you to have already obtained the relevant patches and put them into the right spot (previously mentioned in the README), but I've adjusted the script so it can be run stand-alone. The latest versions of the patches will be automatically cloned from here on GitHub.
